version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  publish-storybook:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build-storybook
      - store_artifacts:
          path: ./storybook-static
      - run: ./bin/update-status
workflows:
  node-tests:
    jobs:
      - publish-storybook
      - node/test
